apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/mysql1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/mysql2
